language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: isRuk45ut5laANnrZTgb4rNgoVZ0KjBiOwQ0QK9I8Pf352qKWK4LYnbSdM/cBMDhC80HkrKSuSUXzoBPQSZTE2s/GOHmS90fkfck05HQixLqwkDvMCNwB4ENHiMtgoz64Co8DnGZaIS1gl66GSeDsUpvX7kMGj3bGIqG23QVfTykeLfkckImu9TNgINiaX5Tg7jZCPYBQIl1MJrNtqiQLVHOy5+WpMmO32iMYOtG1qG6hZME9ryVGUx8b4E2bf1USYldrhD/wgSqnAHD7b1gGOjDzhuVWLCM2PL8WrBeV1ShVs1shXLqQUJvLcy+nQfCkfp+uKBXCMZh0U4gKcgLScBa0VqNoxVGo/cOMHAk13WwxsXPkUUwCRY8/7KDUPzAZBgmzAlNWxdyHcYfwBAnlmgNXPyOlQgvJ54TSBUsBTodKEZhxWz/4VisosZwi7zHm5f8RaWvBugN9YZQG9sPeRy/ktCWMLucf8APgsj4ZJJbRCShMYZt5yA7mcZ9RaNupj/P/gRRqKM2b8HAvs+ZBz/ZLfT4AROBhxRXW9bfBWlwzk/7LllSvpZ0TA8LUGrloBPqRYggQg05IXMYfU93qBgk5WQyJ2jYiYJefIJquEDQTmPKmCD6N8wRpGQzIDjxIY3rUHVJPxlgUlaPaL7ZG5kcvMbEjzHmMo+CyBGpc7o=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: o5wdUofjlbLu3sdB/4aLRoWuMo1swBad2tFwjAWS/qoi9KwKLnpntmquG5lcWsQDA+MEgk+d11sT7Vauop4/MeMI66XH7a/fQJMNa5toVyLJYtDj0GdQttwjyJ3Dheug2LLL8QbusPj59EjvX22RniE3A/pUJNw0QlMI1HWPihwrxHS40GW9uKPJuD3O33qNVpQY5DlvtH5KfU16wQ6aXXM+Nrq2Iv+9SbaOWVpmplNfZ9i/EKuMpHShkx06kt89HIeQubzQzdlCrRhzmEUxwowwzG6WPKbMv4i3LwBW0oQviH2JII1S53CCtSc0evaavqMYdbvftGbv65+qmUv6ukjfg3NfAgdmKijhL+WeUuM32RsHcNox4Z3zM9sFhEEZ5RIG/ICJ82p7R3RVSm8UVjUao4zMAeaMVAFh2RUzi/86uvei+j0VPv2r6vAE47hfmKuertGizgzqu7FUn7o3WUGk4PTXND04rBLtoP6ghXRzP72k/UQ8x8sIJrfYxdZ5AkkioQcgBP2xXBGzefyTFKaW/ZWSzsr/ybYuaaZGnGIQRrfVEa7+R+5uHa5DeNUMp/ZoyGCtgu3FmHp0F2HtOyA6qJ6E21HAp24vZWTfUVqO4Pvuog2R+d23ASsDjutkntMy+u9Olu9UYjlrxprEqkNnxG00/uX0xhTuwLQPeFM=
sudo: false
